[project]
name = "flux-cli"
version = "0.1.0"
description = "Quickly generate images with the Flux Image Models"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests>=2.32.3",
]
